version: '3.3'

services:
  app:
    image: blkndm/skygram:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8000:25000
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
